### ISSUE TITLE
Server repo link broken

### ISSUE THREAD

**Issue by Astrrra** [regimensocial/Citrahold-3DS#2]
HI! I was interested in how citrahold works on the backend (and in possibly self-hosting a modified version for my specific use-case), but it seems that the readme link (https://github.com/regimensocial/Citrahold-Server) just leads to a 404 page. Is that intentional or accidental? 

Btw, thanks a ton for what you've done, I was about to make pretty much the same thing for myself but this is just waaay better than what I could've done :D

**Comment by regimensocial** [comment]
Thank you for your kind words, I'm sure you could've done just as well (or even better!!)

The repository was private? I'm shocked about this, not sure if it reverted at some point or if it's accidentally been private this entire time. I've now sorted it, [please now take a look](https://github.com/regimensocial/Citrahold-Server)... Hopefully the code is up to standard.

I was working on a local fork of Citrahold-PC which would essentially add Citrahold-Server to the PC version, allowing you to do this all over a local network (without me having to a run a server for everyone haha). It's been a while since I worked on this fork, but maybe I'll look into it again.

Please let me know what your specific use-case is and I'll see if it's worth adding some new features (or easy enough haha). If you need any help setting up a self-hosted version, please also let me know. There's no documentation for this right now, but it is fairly simple.
