### ISSUE TITLE
Can't connect to servers

### ISSUE THREAD

**Issue by Fl0-0F** [regimensocial/Citrahold-3DS#6]
i've deleted and reinstalled citrahold on my 3ds multiple times and i cannot connect to servers and i made sure it was the latest version 1.1.1 and when i boot it up on my 3ds it says "Server inaccessible this is NOT OK if this persists, please check the website (which i have done) for a new build" i don't know if its because im in Australia or the servers just don't like me please help

**Comment by Pacomatic1** [comment]
I'm in Canada, works for me. I remember the server was offline for a while but that's done now.
Try connecting again - If it works then we can safely close this issue.

**Comment by regimensocial** [comment]
Hesitant to close this issue because it appears to be a recurring problem.

The server is online and healthy, world-wide. It's hosted in London, so users far away, like those in Australia, will probably have it that it times out for them when Citrahold 3DS does its initial server check.

In the latest build, it will immediately attempt to retry if it fails. If it still fails, just go into settings and manually reconnect.

This issue is more common if you run Citrahold-3DS immediately after booting your 3DS.

**Comment by regimensocial** [comment]
Please let me know if you have any more issues.

**Comment by Fl0-0F** [comment]
Hi thank you its finally been able to connect you can close this issue

**Comment by regimensocial** [comment]
Great to hear!

**Comment by SpudsTheCyan** [comment]
Hi I'm getting this problem now too, and no matter how many times i reconnect its doesn't work.
